language: python
python:
  - "3.6"
cache: pip
install: "pip install -r requirements.txt"

script: python -m unittest test_*.py

after_success:
  - coverage run test_*.py
  - coverage report --show-missing
  - coveralls
