# Config file for automatic testing at travis-ci.org

language: python
matrix:
    include:
      - python: 3.5
        env: TOXENV=py35
      - python: 3.6
        env: TOXENV=py36
      - python: 3.6
        env: TOXENV=flake8

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U tox-travis coveralls

# Command to run tests, e.g. python setup.py test
script: tox

after_success:
  - coveralls
