language: python
python:
  - "3.6"
cache: pip
install: "pip install -r requirements.txt"

script: coverage run --include="./*.py" --omit="./test_*.py" -m unittest test_*.py

after_success:
  - coverage report --show-missing
  - coveralls
